name: Default Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

          - name: Make gradlew executable
            run: chmod +x ./gradlew

          - name: Build with Gradle
            run: ./gradlew -b ci.gradle package

          - name: Run tests
            run: ./gradlew test