name: Default Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
              java-version: '21'
              distribution: 'temurin'

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

          - name: Make gradlew executable
            run: chmod +x ./gradlew

          - name: Grant Permissions to gradlew
            run: chmod +x gradlew
          - name: Test
            run: ./gradlew test --tests "*"

          - name: Test Success
            if: success()
            uses: actions/github-script@0.2.0
            with:
              github-token: ${{ github.token }}
              script: |
                const pull_number = "${{github.event.number}}"
                await github.pulls.createReview({
                  ...context.repo,
                  pull_number,
                  body: "All tests passed.",
                  event: "APPROVE"
                })
          - name: Test Fail
            if: failure()
            uses: actions/github-script@0.2.0
            with:
              github-token: ${{ github.token }}
              script: |
                const pull_number = "${{github.event.number}}"
                await github.pulls.createReview({
                  ...context.repo,
                  pull_number,
                  body: "There is something wrong with test codes.",
                 event: "REQUEST_CHANGES"
                })
                await github.pulls.update({
                  ...context.repo,
                  pull_number,
                  state: "closed"
                })